const { env } = process;

const EMAIL_VERIFICATION_TIMEOUT = +env.EMAIL_VERIFICATION_TIMEOUT;
const PASSWORD_RESET_TIMEOUT = +env.PASSWORD_RESET_TIMEOUT;

module.exports = { EMAIL_VERIFICATION_TIMEOUT, PASSWORD_RESET_TIMEOUT };
